# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2b5c4ca934c718c09fd3637dd7701128143c86bc5170a5fcd0f2b0561a48fcaa62bbc592a47464b7d281a1f5b98811d2d6ea9ad50e76b7bbb9d47c3fc00ec4b

test:
  secret_key_base: 20570756faabe3c1624d04b2cc639f721c820bd2ce469c4087ab62841113e06e853622ad06c633b2db4823e9fb0919043d5570f05ab1f649613a766d39f8bae1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
